apiVersion: v1
kind: Service
metadata:
  name: doc-to-html
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: doc-to-html
  sessionAffinity: None
  type: ClusterIP
