name: Source code scans using some static analyzers
on:
  pull_request:
    paths:
      - "**/*.py"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install dev tooling
      run: make install-dev
    - name: Lint
      run: make lint

  bandit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install dev tooling
      run: make install-dev
    - name: Bandit
      run: make bandit

  check-fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install dev tooling
      run: make install-dev
    - name: check fmt
      run: make fmt-ci
        



